# -*- coding: utf-8 -*-
"""Using the Decision Tree Query through Libra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mLgo2BMORoe_OzvxdRvoWfG787YWD9Fu
"""

!pip install libra

from libra import client

"""Here's the link for the used dataset: 
https://archive.ics.uci.edu/ml/machine-learning-databases/00529/
"""

dia_client = client('diabetes_data_upload.csv')

dia_client.decision_tree_query('Estimate diabetes probability')

"""Let's analyze the model"""

dia_client.analyze()